name: diego_lopez_driving_school_client
description: "Diego Lopez Driving School - Attendance registration and control app"

version: 1.1.17+19

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  archive: ^3.6.1
  bloc: ^8.1.4
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  markdown: ^7.2.2
  package_info_plus: ^8.0.3
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  printing: ^5.13.4
  share_plus: ^10.1.2
  signature: ^5.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/social/
